"""initial tables

Revision ID: 1a3049d306a7
Revises: be9afb52a036
Create Date: 2026-09-14 16:43:32.768640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a3049d306a7'
down_revision = 'be9afb52a036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_catalog',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('track_name', sa.String(length=100), nullable=False),
    sa.Column('level_name', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('course_link', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('governorates',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('segments',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('training_groups',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('governorate_code', sa.String(length=20), nullable=True),
    sa.Column('slice_code', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['governorate_code'], ['governorates.code'], ),
    sa.ForeignKeyConstraint(['slice_code'], ['segments.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('training_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_code', sa.String(length=30), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('applicant_email', sa.String(length=120), nullable=False),
    sa.Column('target_category', sa.String(length=50), nullable=False),
    sa.Column('governorate', sa.String(length=50), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=False),
    sa.Column('course_title', sa.String(length=150), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('days_count', sa.Integer(), nullable=False),
    sa.Column('hours_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('trainer_name', sa.String(length=120), nullable=True),
    sa.Column('trainer_phone', sa.String(length=30), nullable=True),
    sa.Column('hourly_rate_usd', sa.Float(), nullable=True),
    sa.Column('trainer_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('email_message_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_requests')
    op.drop_table('training_groups')
    op.drop_table('users')
    op.drop_table('segments')
    op.drop_table('governorates')
    op.drop_table('course_catalog')
    # ### end Alembic commands ###
