"""Initial migration

Revision ID: be9afb52a036
Revises: 
Create Date: 2026-09-14 16:27:59.496065

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'be9afb52a036'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('insurance_requests')
    with op.batch_alter_table('course_catalog', schema=None) as batch_op:
        batch_op.drop_column('pre_test_link')
        batch_op.drop_column('post_test_link')

    with op.batch_alter_table('training_groups', schema=None) as batch_op:
        batch_op.alter_column('slice_code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_training_groups_segments'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'segments', ['slice_code'], ['code'])

    with op.batch_alter_table('training_requests', schema=None) as batch_op:
        batch_op.alter_column('request_code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=False)
        batch_op.alter_column('applicant_email',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('target_category',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('governorate',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('course_title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'طلب وارد جديد'::character varying"))
        batch_op.alter_column('trainer_name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('trainer_phone',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=True)
        batch_op.alter_column('hourly_rate_usd',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.create_foreign_key(None, 'users', ['applicant_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('must_change_password',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('must_change_password',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('full_name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    with op.batch_alter_table('training_requests', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('hourly_rate_usd',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('trainer_phone',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('trainer_name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'طلب وارد جديد'::character varying"))
        batch_op.alter_column('course_title',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.alter_column('governorate',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('target_category',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('applicant_email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.alter_column('request_code',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('training_groups', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_training_groups_segments'), 'segments', ['slice_code'], ['code'], ondelete='SET NULL')
        batch_op.alter_column('slice_code',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('course_catalog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_test_link', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pre_test_link', sa.TEXT(), autoincrement=False, nullable=True))

    op.create_table('insurance_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('request_code', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('applicant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('governorate', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('group_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('course_title', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('days_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hours_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('trainer_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('trainer_phone', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('trainer_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], name=op.f('insurance_requests_applicant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('insurance_requests_pkey')),
    sa.UniqueConstraint('request_code', name=op.f('insurance_requests_request_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
