"""add link_requests table and test link columns

Revision ID: d6ca2826acf8
Revises: 7f2c4a9d1e33
Create Date: 2026-09-15 13:47:23.939353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6ca2826acf8'
down_revision = '7f2c4a9d1e33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facilitator_id', sa.Integer(), nullable=False),
    sa.Column('facilitator_email', sa.String(length=120), nullable=False),
    sa.Column('course_code', sa.String(length=30), nullable=False),
    sa.Column('test_type', sa.String(length=10), nullable=False),
    sa.Column('requested_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('window_end', sa.DateTime(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_code'], ['course_catalog.code'], ),
    sa.ForeignKeyConstraint(['facilitator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('course_catalog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pre_test_link', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('post_test_link', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_catalog', schema=None) as batch_op:
        batch_op.drop_column('post_test_link')
        batch_op.drop_column('pre_test_link')

    op.drop_table('link_requests')
    # ### end Alembic commands ###
